// Code generated by ent, DO NOT EDIT.

package policybinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLTE(FieldID, id))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldCreated, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldCreatedBy, v))
}

// PolicyID applies equality check predicate on the "policy_id" field. It's identical to PolicyIDEQ.
func PolicyID(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldPolicyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldGroupID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldAgentID, v))
}

// PrincipalTypeEQ applies the EQ predicate on the "principal_type" field.
func PrincipalTypeEQ(v PrincipalType) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldPrincipalType, v))
}

// PrincipalTypeNEQ applies the NEQ predicate on the "principal_type" field.
func PrincipalTypeNEQ(v PrincipalType) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldPrincipalType, v))
}

// PrincipalTypeIn applies the In predicate on the "principal_type" field.
func PrincipalTypeIn(vs ...PrincipalType) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldPrincipalType, vs...))
}

// PrincipalTypeNotIn applies the NotIn predicate on the "principal_type" field.
func PrincipalTypeNotIn(vs ...PrincipalType) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldPrincipalType, vs...))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLTE(FieldCreated, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldContainsFold(FieldCreatedBy, v))
}

// PolicyIDEQ applies the EQ predicate on the "policy_id" field.
func PolicyIDEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldPolicyID, v))
}

// PolicyIDNEQ applies the NEQ predicate on the "policy_id" field.
func PolicyIDNEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldPolicyID, v))
}

// PolicyIDIn applies the In predicate on the "policy_id" field.
func PolicyIDIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldPolicyID, vs...))
}

// PolicyIDNotIn applies the NotIn predicate on the "policy_id" field.
func PolicyIDNotIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldPolicyID, vs...))
}

// PolicyIDIsNil applies the IsNil predicate on the "policy_id" field.
func PolicyIDIsNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIsNull(FieldPolicyID))
}

// PolicyIDNotNil applies the NotNil predicate on the "policy_id" field.
func PolicyIDNotNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotNull(FieldPolicyID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotNull(FieldUserID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotNull(FieldGroupID))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...uuid.UUID) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.FieldNotNull(FieldAgentID))
}

// HasPolicy applies the HasEdge predicate on the "policy" edge.
func HasPolicy() predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PolicyTable, PolicyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPolicyWith applies the HasEdge predicate on the "policy" edge with a given conditions (other predicates).
func HasPolicyWith(preds ...predicate.AccessPolicy) predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := newPolicyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.PolicyBinding {
	return predicate.PolicyBinding(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PolicyBinding) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PolicyBinding) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PolicyBinding) predicate.PolicyBinding {
	return predicate.PolicyBinding(sql.NotPredicates(p))
}
