schema_version: "1"
active_profile: local
default_template: default
default_harness_config: claude
hub:
    endpoint: http://localhost:8080
cli:
    autohelp: true
runtimes:
    container:
        type: container
    docker:
        type: docker
    kubernetes:
        type: kubernetes
profiles:
    local:
        runtime: container
        env:
            GOOGLE_CLOUD_PROJECT: duet01
            GOOGLE_CLOUD_REGION: global
    remote:
        runtime: kubernetes
