// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessPolicy is the predicate function for accesspolicy builders.
type AccessPolicy func(*sql.Selector)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMembership is the predicate function for groupmembership builders.
type GroupMembership func(*sql.Selector)

// Grove is the predicate function for grove builders.
type Grove func(*sql.Selector)

// PolicyBinding is the predicate function for policybinding builders.
type PolicyBinding func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
