// Code generated by ent, DO NOT EDIT.

package groupmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLTE(FieldID, id))
}

// AddedBy applies equality check predicate on the "added_by" field. It's identical to AddedByEQ.
func AddedBy(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAddedBy, v))
}

// AddedAt applies equality check predicate on the "added_at" field. It's identical to AddedAtEQ.
func AddedAt(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAddedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldGroupID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldUserID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAgentID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldRole, vs...))
}

// AddedByEQ applies the EQ predicate on the "added_by" field.
func AddedByEQ(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAddedBy, v))
}

// AddedByNEQ applies the NEQ predicate on the "added_by" field.
func AddedByNEQ(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldAddedBy, v))
}

// AddedByIn applies the In predicate on the "added_by" field.
func AddedByIn(vs ...string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldAddedBy, vs...))
}

// AddedByNotIn applies the NotIn predicate on the "added_by" field.
func AddedByNotIn(vs ...string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldAddedBy, vs...))
}

// AddedByGT applies the GT predicate on the "added_by" field.
func AddedByGT(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGT(FieldAddedBy, v))
}

// AddedByGTE applies the GTE predicate on the "added_by" field.
func AddedByGTE(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGTE(FieldAddedBy, v))
}

// AddedByLT applies the LT predicate on the "added_by" field.
func AddedByLT(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLT(FieldAddedBy, v))
}

// AddedByLTE applies the LTE predicate on the "added_by" field.
func AddedByLTE(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLTE(FieldAddedBy, v))
}

// AddedByContains applies the Contains predicate on the "added_by" field.
func AddedByContains(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldContains(FieldAddedBy, v))
}

// AddedByHasPrefix applies the HasPrefix predicate on the "added_by" field.
func AddedByHasPrefix(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldHasPrefix(FieldAddedBy, v))
}

// AddedByHasSuffix applies the HasSuffix predicate on the "added_by" field.
func AddedByHasSuffix(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldHasSuffix(FieldAddedBy, v))
}

// AddedByIsNil applies the IsNil predicate on the "added_by" field.
func AddedByIsNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIsNull(FieldAddedBy))
}

// AddedByNotNil applies the NotNil predicate on the "added_by" field.
func AddedByNotNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotNull(FieldAddedBy))
}

// AddedByEqualFold applies the EqualFold predicate on the "added_by" field.
func AddedByEqualFold(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEqualFold(FieldAddedBy, v))
}

// AddedByContainsFold applies the ContainsFold predicate on the "added_by" field.
func AddedByContainsFold(v string) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldContainsFold(FieldAddedBy, v))
}

// AddedAtEQ applies the EQ predicate on the "added_at" field.
func AddedAtEQ(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAddedAt, v))
}

// AddedAtNEQ applies the NEQ predicate on the "added_at" field.
func AddedAtNEQ(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldAddedAt, v))
}

// AddedAtIn applies the In predicate on the "added_at" field.
func AddedAtIn(vs ...time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldAddedAt, vs...))
}

// AddedAtNotIn applies the NotIn predicate on the "added_at" field.
func AddedAtNotIn(vs ...time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldAddedAt, vs...))
}

// AddedAtGT applies the GT predicate on the "added_at" field.
func AddedAtGT(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGT(FieldAddedAt, v))
}

// AddedAtGTE applies the GTE predicate on the "added_at" field.
func AddedAtGTE(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldGTE(FieldAddedAt, v))
}

// AddedAtLT applies the LT predicate on the "added_at" field.
func AddedAtLT(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLT(FieldAddedAt, v))
}

// AddedAtLTE applies the LTE predicate on the "added_at" field.
func AddedAtLTE(v time.Time) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldLTE(FieldAddedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldGroupID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotNull(FieldUserID))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...uuid.UUID) predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.GroupMembership {
	return predicate.GroupMembership(sql.FieldNotNull(FieldAgentID))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.GroupMembership {
	return predicate.GroupMembership(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupMembership) predicate.GroupMembership {
	return predicate.GroupMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupMembership) predicate.GroupMembership {
	return predicate.GroupMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupMembership) predicate.GroupMembership {
	return predicate.GroupMembership(sql.NotPredicates(p))
}
