// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/schema"
	"github.com/google/uuid"
)

// AccessPolicy is the model entity for the AccessPolicy schema.
type AccessPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType accesspolicy.ScopeType `json:"scope_type,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID string `json:"resource_id,omitempty"`
	// Actions holds the value of the "actions" field.
	Actions []string `json:"actions,omitempty"`
	// Effect holds the value of the "effect" field.
	Effect accesspolicy.Effect `json:"effect,omitempty"`
	// Conditions holds the value of the "conditions" field.
	Conditions *schema.PolicyConditions `json:"conditions,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels map[string]string `json:"labels,omitempty"`
	// Annotations holds the value of the "annotations" field.
	Annotations map[string]string `json:"annotations,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Updated holds the value of the "updated" field.
	Updated time.Time `json:"updated,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessPolicyQuery when eager-loading is set.
	Edges        AccessPolicyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccessPolicyEdges holds the relations/edges for other nodes in the graph.
type AccessPolicyEdges struct {
	// Bindings holds the value of the bindings edge.
	Bindings []*PolicyBinding `json:"bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BindingsOrErr returns the Bindings value or an error if the edge
// was not loaded in eager-loading.
func (e AccessPolicyEdges) BindingsOrErr() ([]*PolicyBinding, error) {
	if e.loadedTypes[0] {
		return e.Bindings, nil
	}
	return nil, &NotLoadedError{edge: "bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesspolicy.FieldActions, accesspolicy.FieldConditions, accesspolicy.FieldLabels, accesspolicy.FieldAnnotations:
			values[i] = new([]byte)
		case accesspolicy.FieldPriority:
			values[i] = new(sql.NullInt64)
		case accesspolicy.FieldName, accesspolicy.FieldDescription, accesspolicy.FieldScopeType, accesspolicy.FieldScopeID, accesspolicy.FieldResourceType, accesspolicy.FieldResourceID, accesspolicy.FieldEffect, accesspolicy.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case accesspolicy.FieldCreated, accesspolicy.FieldUpdated:
			values[i] = new(sql.NullTime)
		case accesspolicy.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessPolicy fields.
func (_m *AccessPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesspolicy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case accesspolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accesspolicy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case accesspolicy.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = accesspolicy.ScopeType(value.String)
			}
		case accesspolicy.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case accesspolicy.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case accesspolicy.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.String
			}
		case accesspolicy.FieldActions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field actions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Actions); err != nil {
					return fmt.Errorf("unmarshal field actions: %w", err)
				}
			}
		case accesspolicy.FieldEffect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effect", values[i])
			} else if value.Valid {
				_m.Effect = accesspolicy.Effect(value.String)
			}
		case accesspolicy.FieldConditions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field conditions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Conditions); err != nil {
					return fmt.Errorf("unmarshal field conditions: %w", err)
				}
			}
		case accesspolicy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case accesspolicy.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case accesspolicy.FieldAnnotations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field annotations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Annotations); err != nil {
					return fmt.Errorf("unmarshal field annotations: %w", err)
				}
			}
		case accesspolicy.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case accesspolicy.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				_m.Updated = value.Time
			}
		case accesspolicy.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *AccessPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBindings queries the "bindings" edge of the AccessPolicy entity.
func (_m *AccessPolicy) QueryBindings() *PolicyBindingQuery {
	return NewAccessPolicyClient(_m.config).QueryBindings(_m)
}

// Update returns a builder for updating this AccessPolicy.
// Note that you need to call AccessPolicy.Unwrap() before calling this method if this AccessPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessPolicy) Update() *AccessPolicyUpdateOne {
	return NewAccessPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessPolicy) Unwrap() *AccessPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("AccessPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScopeType))
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(_m.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("actions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Actions))
	builder.WriteString(", ")
	builder.WriteString("effect=")
	builder.WriteString(fmt.Sprintf("%v", _m.Effect))
	builder.WriteString(", ")
	builder.WriteString("conditions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Conditions))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("annotations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Annotations))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(_m.Updated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// AccessPolicies is a parsable slice of AccessPolicy.
type AccessPolicies []*AccessPolicy
