// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/schema"
	"github.com/google/uuid"
)

// AccessPolicyCreate is the builder for creating a AccessPolicy entity.
type AccessPolicyCreate struct {
	config
	mutation *AccessPolicyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AccessPolicyCreate) SetName(v string) *AccessPolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AccessPolicyCreate) SetDescription(v string) *AccessPolicyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableDescription(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *AccessPolicyCreate) SetScopeType(v accesspolicy.ScopeType) *AccessPolicyCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *AccessPolicyCreate) SetScopeID(v string) *AccessPolicyCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableScopeID(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *AccessPolicyCreate) SetResourceType(v string) *AccessPolicyCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *AccessPolicyCreate) SetResourceID(v string) *AccessPolicyCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableResourceID(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetActions sets the "actions" field.
func (_c *AccessPolicyCreate) SetActions(v []string) *AccessPolicyCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetEffect sets the "effect" field.
func (_c *AccessPolicyCreate) SetEffect(v accesspolicy.Effect) *AccessPolicyCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *AccessPolicyCreate) SetConditions(v *schema.PolicyConditions) *AccessPolicyCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *AccessPolicyCreate) SetPriority(v int) *AccessPolicyCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillablePriority(v *int) *AccessPolicyCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *AccessPolicyCreate) SetLabels(v map[string]string) *AccessPolicyCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetAnnotations sets the "annotations" field.
func (_c *AccessPolicyCreate) SetAnnotations(v map[string]string) *AccessPolicyCreate {
	_c.mutation.SetAnnotations(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *AccessPolicyCreate) SetCreated(v time.Time) *AccessPolicyCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableCreated(v *time.Time) *AccessPolicyCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *AccessPolicyCreate) SetUpdated(v time.Time) *AccessPolicyCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableUpdated(v *time.Time) *AccessPolicyCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AccessPolicyCreate) SetCreatedBy(v string) *AccessPolicyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableCreatedBy(v *string) *AccessPolicyCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccessPolicyCreate) SetID(v uuid.UUID) *AccessPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccessPolicyCreate) SetNillableID(v *uuid.UUID) *AccessPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBindingIDs adds the "bindings" edge to the PolicyBinding entity by IDs.
func (_c *AccessPolicyCreate) AddBindingIDs(ids ...uuid.UUID) *AccessPolicyCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the PolicyBinding entity.
func (_c *AccessPolicyCreate) AddBindings(v ...*PolicyBinding) *AccessPolicyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// Mutation returns the AccessPolicyMutation object of the builder.
func (_c *AccessPolicyCreate) Mutation() *AccessPolicyMutation {
	return _c.mutation
}

// Save creates the AccessPolicy in the database.
func (_c *AccessPolicyCreate) Save(ctx context.Context) (*AccessPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessPolicyCreate) SaveX(ctx context.Context) *AccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessPolicyCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := accesspolicy.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := accesspolicy.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := accesspolicy.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := accesspolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessPolicyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccessPolicy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accesspolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccessPolicy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "AccessPolicy.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := accesspolicy.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "AccessPolicy.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "AccessPolicy.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := accesspolicy.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AccessPolicy.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "AccessPolicy.effect"`)}
	}
	if v, ok := _c.mutation.Effect(); ok {
		if err := accesspolicy.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "AccessPolicy.effect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "AccessPolicy.priority"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "AccessPolicy.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "AccessPolicy.updated"`)}
	}
	return nil
}

func (_c *AccessPolicyCreate) sqlSave(ctx context.Context) (*AccessPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessPolicyCreate) createSpec() (*AccessPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesspolicy.Table, sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accesspolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(accesspolicy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(accesspolicy.FieldScopeType, field.TypeEnum, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(accesspolicy.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(accesspolicy.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(accesspolicy.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(accesspolicy.FieldActions, field.TypeJSON, value)
		_node.Actions = value
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(accesspolicy.FieldEffect, field.TypeEnum, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(accesspolicy.FieldConditions, field.TypeJSON, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(accesspolicy.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(accesspolicy.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Annotations(); ok {
		_spec.SetField(accesspolicy.FieldAnnotations, field.TypeJSON, value)
		_node.Annotations = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(accesspolicy.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(accesspolicy.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(accesspolicy.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesspolicy.BindingsTable,
			Columns: []string{accesspolicy.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessPolicyCreateBulk is the builder for creating many AccessPolicy entities in bulk.
type AccessPolicyCreateBulk struct {
	config
	err      error
	builders []*AccessPolicyCreate
}

// Save creates the AccessPolicy entities in the database.
func (_c *AccessPolicyCreateBulk) Save(ctx context.Context) ([]*AccessPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessPolicyCreateBulk) SaveX(ctx context.Context) []*AccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
