// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/groupmembership"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AgentUpdate) SetSlug(v string) *AgentUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableSlug(v *string) *AgentUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdate) SetName(v string) *AgentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableName(v *string) *AgentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTemplate sets the "template" field.
func (_u *AgentUpdate) SetTemplate(v string) *AgentUpdate {
	_u.mutation.SetTemplate(v)
	return _u
}

// SetNillableTemplate sets the "template" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableTemplate(v *string) *AgentUpdate {
	if v != nil {
		_u.SetTemplate(*v)
	}
	return _u
}

// ClearTemplate clears the value of the "template" field.
func (_u *AgentUpdate) ClearTemplate() *AgentUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// SetGroveID sets the "grove_id" field.
func (_u *AgentUpdate) SetGroveID(v uuid.UUID) *AgentUpdate {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableGroveID(v *uuid.UUID) *AgentUpdate {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdate) SetStatus(v agent.Status) *AgentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableStatus(v *agent.Status) *AgentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AgentUpdate) SetCreatedBy(v uuid.UUID) *AgentUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableCreatedBy(v *uuid.UUID) *AgentUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AgentUpdate) ClearCreatedBy() *AgentUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *AgentUpdate) SetOwnerID(v uuid.UUID) *AgentUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableOwnerID(v *uuid.UUID) *AgentUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *AgentUpdate) ClearOwnerID() *AgentUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetDelegationEnabled sets the "delegation_enabled" field.
func (_u *AgentUpdate) SetDelegationEnabled(v bool) *AgentUpdate {
	_u.mutation.SetDelegationEnabled(v)
	return _u
}

// SetNillableDelegationEnabled sets the "delegation_enabled" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDelegationEnabled(v *bool) *AgentUpdate {
	if v != nil {
		_u.SetDelegationEnabled(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *AgentUpdate) SetVisibility(v string) *AgentUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableVisibility(v *string) *AgentUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AgentUpdate) SetUpdated(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetGrove sets the "grove" edge to the Grove entity.
func (_u *AgentUpdate) SetGrove(v *Grove) *AgentUpdate {
	return _u.SetGroveID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AgentUpdate) SetCreatorID(id uuid.UUID) *AgentUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *AgentUpdate) SetNillableCreatorID(id *uuid.UUID) *AgentUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AgentUpdate) SetCreator(v *User) *AgentUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *AgentUpdate) SetOwner(v *User) *AgentUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the GroupMembership entity by IDs.
func (_u *AgentUpdate) AddMembershipIDs(ids ...uuid.UUID) *AgentUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the GroupMembership entity.
func (_u *AgentUpdate) AddMemberships(v ...*GroupMembership) *AgentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddPolicyBindingIDs adds the "policy_bindings" edge to the PolicyBinding entity by IDs.
func (_u *AgentUpdate) AddPolicyBindingIDs(ids ...uuid.UUID) *AgentUpdate {
	_u.mutation.AddPolicyBindingIDs(ids...)
	return _u
}

// AddPolicyBindings adds the "policy_bindings" edges to the PolicyBinding entity.
func (_u *AgentUpdate) AddPolicyBindings(v ...*PolicyBinding) *AgentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyBindingIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearGrove clears the "grove" edge to the Grove entity.
func (_u *AgentUpdate) ClearGrove() *AgentUpdate {
	_u.mutation.ClearGrove()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AgentUpdate) ClearCreator() *AgentUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *AgentUpdate) ClearOwner() *AgentUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMemberships clears all "memberships" edges to the GroupMembership entity.
func (_u *AgentUpdate) ClearMemberships() *AgentUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to GroupMembership entities by IDs.
func (_u *AgentUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *AgentUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to GroupMembership entities.
func (_u *AgentUpdate) RemoveMemberships(v ...*GroupMembership) *AgentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearPolicyBindings clears all "policy_bindings" edges to the PolicyBinding entity.
func (_u *AgentUpdate) ClearPolicyBindings() *AgentUpdate {
	_u.mutation.ClearPolicyBindings()
	return _u
}

// RemovePolicyBindingIDs removes the "policy_bindings" edge to PolicyBinding entities by IDs.
func (_u *AgentUpdate) RemovePolicyBindingIDs(ids ...uuid.UUID) *AgentUpdate {
	_u.mutation.RemovePolicyBindingIDs(ids...)
	return _u
}

// RemovePolicyBindings removes "policy_bindings" edges to PolicyBinding entities.
func (_u *AgentUpdate) RemovePolicyBindings(v ...*PolicyBinding) *AgentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := agent.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := agent.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Agent.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	if _u.mutation.GroveCleared() && len(_u.mutation.GroveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.grove"`)
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(agent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Template(); ok {
		_spec.SetField(agent.FieldTemplate, field.TypeString, value)
	}
	if _u.mutation.TemplateCleared() {
		_spec.ClearField(agent.FieldTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DelegationEnabled(); ok {
		_spec.SetField(agent.FieldDelegationEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(agent.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(agent.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.GroveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.GroveTable,
			Columns: []string{agent.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.GroveTable,
			Columns: []string{agent.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.OwnerTable,
			Columns: []string{agent.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.OwnerTable,
			Columns: []string{agent.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PolicyBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPolicyBindingsIDs(); len(nodes) > 0 && !_u.mutation.PolicyBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetSlug sets the "slug" field.
func (_u *AgentUpdateOne) SetSlug(v string) *AgentUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableSlug(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdateOne) SetName(v string) *AgentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableName(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTemplate sets the "template" field.
func (_u *AgentUpdateOne) SetTemplate(v string) *AgentUpdateOne {
	_u.mutation.SetTemplate(v)
	return _u
}

// SetNillableTemplate sets the "template" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableTemplate(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetTemplate(*v)
	}
	return _u
}

// ClearTemplate clears the value of the "template" field.
func (_u *AgentUpdateOne) ClearTemplate() *AgentUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// SetGroveID sets the "grove_id" field.
func (_u *AgentUpdateOne) SetGroveID(v uuid.UUID) *AgentUpdateOne {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableGroveID(v *uuid.UUID) *AgentUpdateOne {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdateOne) SetStatus(v agent.Status) *AgentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableStatus(v *agent.Status) *AgentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AgentUpdateOne) SetCreatedBy(v uuid.UUID) *AgentUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *AgentUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AgentUpdateOne) ClearCreatedBy() *AgentUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *AgentUpdateOne) SetOwnerID(v uuid.UUID) *AgentUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableOwnerID(v *uuid.UUID) *AgentUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *AgentUpdateOne) ClearOwnerID() *AgentUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetDelegationEnabled sets the "delegation_enabled" field.
func (_u *AgentUpdateOne) SetDelegationEnabled(v bool) *AgentUpdateOne {
	_u.mutation.SetDelegationEnabled(v)
	return _u
}

// SetNillableDelegationEnabled sets the "delegation_enabled" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDelegationEnabled(v *bool) *AgentUpdateOne {
	if v != nil {
		_u.SetDelegationEnabled(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *AgentUpdateOne) SetVisibility(v string) *AgentUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableVisibility(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *AgentUpdateOne) SetUpdated(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetGrove sets the "grove" edge to the Grove entity.
func (_u *AgentUpdateOne) SetGrove(v *Grove) *AgentUpdateOne {
	return _u.SetGroveID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AgentUpdateOne) SetCreatorID(id uuid.UUID) *AgentUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableCreatorID(id *uuid.UUID) *AgentUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AgentUpdateOne) SetCreator(v *User) *AgentUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *AgentUpdateOne) SetOwner(v *User) *AgentUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the GroupMembership entity by IDs.
func (_u *AgentUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *AgentUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the GroupMembership entity.
func (_u *AgentUpdateOne) AddMemberships(v ...*GroupMembership) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddPolicyBindingIDs adds the "policy_bindings" edge to the PolicyBinding entity by IDs.
func (_u *AgentUpdateOne) AddPolicyBindingIDs(ids ...uuid.UUID) *AgentUpdateOne {
	_u.mutation.AddPolicyBindingIDs(ids...)
	return _u
}

// AddPolicyBindings adds the "policy_bindings" edges to the PolicyBinding entity.
func (_u *AgentUpdateOne) AddPolicyBindings(v ...*PolicyBinding) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyBindingIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearGrove clears the "grove" edge to the Grove entity.
func (_u *AgentUpdateOne) ClearGrove() *AgentUpdateOne {
	_u.mutation.ClearGrove()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AgentUpdateOne) ClearCreator() *AgentUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *AgentUpdateOne) ClearOwner() *AgentUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMemberships clears all "memberships" edges to the GroupMembership entity.
func (_u *AgentUpdateOne) ClearMemberships() *AgentUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to GroupMembership entities by IDs.
func (_u *AgentUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *AgentUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to GroupMembership entities.
func (_u *AgentUpdateOne) RemoveMemberships(v ...*GroupMembership) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearPolicyBindings clears all "policy_bindings" edges to the PolicyBinding entity.
func (_u *AgentUpdateOne) ClearPolicyBindings() *AgentUpdateOne {
	_u.mutation.ClearPolicyBindings()
	return _u
}

// RemovePolicyBindingIDs removes the "policy_bindings" edge to PolicyBinding entities by IDs.
func (_u *AgentUpdateOne) RemovePolicyBindingIDs(ids ...uuid.UUID) *AgentUpdateOne {
	_u.mutation.RemovePolicyBindingIDs(ids...)
	return _u
}

// RemovePolicyBindings removes "policy_bindings" edges to PolicyBinding entities.
func (_u *AgentUpdateOne) RemovePolicyBindings(v ...*PolicyBinding) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyBindingIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := agent.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := agent.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Agent.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	if _u.mutation.GroveCleared() && len(_u.mutation.GroveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.grove"`)
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(agent.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Template(); ok {
		_spec.SetField(agent.FieldTemplate, field.TypeString, value)
	}
	if _u.mutation.TemplateCleared() {
		_spec.ClearField(agent.FieldTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DelegationEnabled(); ok {
		_spec.SetField(agent.FieldDelegationEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(agent.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(agent.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.GroveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.GroveTable,
			Columns: []string{agent.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.GroveTable,
			Columns: []string{agent.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.OwnerTable,
			Columns: []string{agent.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.OwnerTable,
			Columns: []string{agent.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MembershipsTable,
			Columns: []string{agent.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PolicyBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPolicyBindingsIDs(); len(nodes) > 0 && !_u.mutation.PolicyBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.PolicyBindingsTable,
			Columns: []string{agent.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
