// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// Agent is the model entity for the Agent schema.
type Agent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Template holds the value of the "template" field.
	Template string `json:"template,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID uuid.UUID `json:"grove_id,omitempty"`
	// Status holds the value of the "status" field.
	Status agent.Status `json:"status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID *uuid.UUID `json:"owner_id,omitempty"`
	// DelegationEnabled holds the value of the "delegation_enabled" field.
	DelegationEnabled bool `json:"delegation_enabled,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Updated holds the value of the "updated" field.
	Updated time.Time `json:"updated,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentQuery when eager-loading is set.
	Edges        AgentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentEdges holds the relations/edges for other nodes in the graph.
type AgentEdges struct {
	// Grove holds the value of the grove edge.
	Grove *Grove `json:"grove,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Memberships holds the value of the memberships edge.
	Memberships []*GroupMembership `json:"memberships,omitempty"`
	// PolicyBindings holds the value of the policy_bindings edge.
	PolicyBindings []*PolicyBinding `json:"policy_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// GroveOrErr returns the Grove value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEdges) GroveOrErr() (*Grove, error) {
	if e.Grove != nil {
		return e.Grove, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: grove.Label}
	}
	return nil, &NotLoadedError{edge: "grove"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembershipsOrErr returns the Memberships value or an error if the edge
// was not loaded in eager-loading.
func (e AgentEdges) MembershipsOrErr() ([]*GroupMembership, error) {
	if e.loadedTypes[3] {
		return e.Memberships, nil
	}
	return nil, &NotLoadedError{edge: "memberships"}
}

// PolicyBindingsOrErr returns the PolicyBindings value or an error if the edge
// was not loaded in eager-loading.
func (e AgentEdges) PolicyBindingsOrErr() ([]*PolicyBinding, error) {
	if e.loadedTypes[4] {
		return e.PolicyBindings, nil
	}
	return nil, &NotLoadedError{edge: "policy_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Agent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agent.FieldCreatedBy, agent.FieldOwnerID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case agent.FieldDelegationEnabled:
			values[i] = new(sql.NullBool)
		case agent.FieldSlug, agent.FieldName, agent.FieldTemplate, agent.FieldStatus, agent.FieldVisibility:
			values[i] = new(sql.NullString)
		case agent.FieldCreated, agent.FieldUpdated:
			values[i] = new(sql.NullTime)
		case agent.FieldID, agent.FieldGroveID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Agent fields.
func (_m *Agent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agent.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case agent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agent.FieldTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template", values[i])
			} else if value.Valid {
				_m.Template = value.String
			}
		case agent.FieldGroveID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value != nil {
				_m.GroveID = *value
			}
		case agent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agent.Status(value.String)
			}
		case agent.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case agent.FieldOwnerID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = new(uuid.UUID)
				*_m.OwnerID = *value.S.(*uuid.UUID)
			}
		case agent.FieldDelegationEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field delegation_enabled", values[i])
			} else if value.Valid {
				_m.DelegationEnabled = value.Bool
			}
		case agent.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		case agent.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case agent.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				_m.Updated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Agent.
// This includes values selected through modifiers, order, etc.
func (_m *Agent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGrove queries the "grove" edge of the Agent entity.
func (_m *Agent) QueryGrove() *GroveQuery {
	return NewAgentClient(_m.config).QueryGrove(_m)
}

// QueryCreator queries the "creator" edge of the Agent entity.
func (_m *Agent) QueryCreator() *UserQuery {
	return NewAgentClient(_m.config).QueryCreator(_m)
}

// QueryOwner queries the "owner" edge of the Agent entity.
func (_m *Agent) QueryOwner() *UserQuery {
	return NewAgentClient(_m.config).QueryOwner(_m)
}

// QueryMemberships queries the "memberships" edge of the Agent entity.
func (_m *Agent) QueryMemberships() *GroupMembershipQuery {
	return NewAgentClient(_m.config).QueryMemberships(_m)
}

// QueryPolicyBindings queries the "policy_bindings" edge of the Agent entity.
func (_m *Agent) QueryPolicyBindings() *PolicyBindingQuery {
	return NewAgentClient(_m.config).QueryPolicyBindings(_m)
}

// Update returns a builder for updating this Agent.
// Note that you need to call Agent.Unwrap() before calling this method if this Agent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Agent) Update() *AgentUpdateOne {
	return NewAgentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Agent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Agent) Unwrap() *Agent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Agent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Agent) String() string {
	var builder strings.Builder
	builder.WriteString("Agent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("template=")
	builder.WriteString(_m.Template)
	builder.WriteString(", ")
	builder.WriteString("grove_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroveID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OwnerID; v != nil {
		builder.WriteString("owner_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("delegation_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DelegationEnabled))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(_m.Updated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Agents is a parsable slice of Agent.
type Agents []*Agent
