// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/groupmembership"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// GroupCreate is the builder for creating a Group entity.
type GroupCreate struct {
	config
	mutation *GroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GroupCreate) SetName(v string) *GroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *GroupCreate) SetSlug(v string) *GroupCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *GroupCreate) SetDescription(v string) *GroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GroupCreate) SetNillableDescription(v *string) *GroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGroupType sets the "group_type" field.
func (_c *GroupCreate) SetGroupType(v group.GroupType) *GroupCreate {
	_c.mutation.SetGroupType(v)
	return _c
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_c *GroupCreate) SetNillableGroupType(v *group.GroupType) *GroupCreate {
	if v != nil {
		_c.SetGroupType(*v)
	}
	return _c
}

// SetGroveID sets the "grove_id" field.
func (_c *GroupCreate) SetGroveID(v uuid.UUID) *GroupCreate {
	_c.mutation.SetGroveID(v)
	return _c
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_c *GroupCreate) SetNillableGroveID(v *uuid.UUID) *GroupCreate {
	if v != nil {
		_c.SetGroveID(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *GroupCreate) SetLabels(v map[string]string) *GroupCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetAnnotations sets the "annotations" field.
func (_c *GroupCreate) SetAnnotations(v map[string]string) *GroupCreate {
	_c.mutation.SetAnnotations(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *GroupCreate) SetCreated(v time.Time) *GroupCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *GroupCreate) SetNillableCreated(v *time.Time) *GroupCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *GroupCreate) SetUpdated(v time.Time) *GroupCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *GroupCreate) SetNillableUpdated(v *time.Time) *GroupCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GroupCreate) SetCreatedBy(v string) *GroupCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GroupCreate) SetNillableCreatedBy(v *string) *GroupCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *GroupCreate) SetOwnerID(v uuid.UUID) *GroupCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *GroupCreate) SetNillableOwnerID(v *uuid.UUID) *GroupCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupCreate) SetID(v uuid.UUID) *GroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroupCreate) SetNillableID(v *uuid.UUID) *GroupCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMembershipIDs adds the "memberships" edge to the GroupMembership entity by IDs.
func (_c *GroupCreate) AddMembershipIDs(ids ...uuid.UUID) *GroupCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the GroupMembership entity.
func (_c *GroupCreate) AddMemberships(v ...*GroupMembership) *GroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddParentGroupIDs adds the "parent_groups" edge to the Group entity by IDs.
func (_c *GroupCreate) AddParentGroupIDs(ids ...uuid.UUID) *GroupCreate {
	_c.mutation.AddParentGroupIDs(ids...)
	return _c
}

// AddParentGroups adds the "parent_groups" edges to the Group entity.
func (_c *GroupCreate) AddParentGroups(v ...*Group) *GroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParentGroupIDs(ids...)
}

// AddChildGroupIDs adds the "child_groups" edge to the Group entity by IDs.
func (_c *GroupCreate) AddChildGroupIDs(ids ...uuid.UUID) *GroupCreate {
	_c.mutation.AddChildGroupIDs(ids...)
	return _c
}

// AddChildGroups adds the "child_groups" edges to the Group entity.
func (_c *GroupCreate) AddChildGroups(v ...*Group) *GroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildGroupIDs(ids...)
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *GroupCreate) SetOwner(v *User) *GroupCreate {
	return _c.SetOwnerID(v.ID)
}

// AddPolicyBindingIDs adds the "policy_bindings" edge to the PolicyBinding entity by IDs.
func (_c *GroupCreate) AddPolicyBindingIDs(ids ...uuid.UUID) *GroupCreate {
	_c.mutation.AddPolicyBindingIDs(ids...)
	return _c
}

// AddPolicyBindings adds the "policy_bindings" edges to the PolicyBinding entity.
func (_c *GroupCreate) AddPolicyBindings(v ...*PolicyBinding) *GroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPolicyBindingIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_c *GroupCreate) Mutation() *GroupMutation {
	return _c.mutation
}

// Save creates the Group in the database.
func (_c *GroupCreate) Save(ctx context.Context) (*Group, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupCreate) SaveX(ctx context.Context) *Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupCreate) defaults() {
	if _, ok := _c.mutation.GroupType(); !ok {
		v := group.DefaultGroupType
		_c.mutation.SetGroupType(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := group.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := group.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := group.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Group.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Group.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := group.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Group.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupType(); !ok {
		return &ValidationError{Name: "group_type", err: errors.New(`ent: missing required field "Group.group_type"`)}
	}
	if v, ok := _c.mutation.GroupType(); ok {
		if err := group.GroupTypeValidator(v); err != nil {
			return &ValidationError{Name: "group_type", err: fmt.Errorf(`ent: validator failed for field "Group.group_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Group.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Group.updated"`)}
	}
	return nil
}

func (_c *GroupCreate) sqlSave(ctx context.Context) (*Group, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupCreate) createSpec() (*Group, *sqlgraph.CreateSpec) {
	var (
		_node = &Group{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(group.Table, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(group.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.GroupType(); ok {
		_spec.SetField(group.FieldGroupType, field.TypeEnum, value)
		_node.GroupType = value
	}
	if value, ok := _c.mutation.GroveID(); ok {
		_spec.SetField(group.FieldGroveID, field.TypeUUID, value)
		_node.GroveID = &value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(group.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Annotations(); ok {
		_spec.SetField(group.FieldAnnotations, field.TypeJSON, value)
		_node.Annotations = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(group.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(group.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(group.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembershipsTable,
			Columns: []string{group.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.ParentGroupsTable,
			Columns: group.ParentGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.ChildGroupsTable,
			Columns: group.ChildGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.OwnerTable,
			Columns: []string{group.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PolicyBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   group.PolicyBindingsTable,
			Columns: []string{group.PolicyBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupCreateBulk is the builder for creating many Group entities in bulk.
type GroupCreateBulk struct {
	config
	err      error
	builders []*GroupCreate
}

// Save creates the Group entities in the database.
func (_c *GroupCreateBulk) Save(ctx context.Context) ([]*Group, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Group, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupCreateBulk) SaveX(ctx context.Context) []*Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
