// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/groupmembership"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// GroupMembershipCreate is the builder for creating a GroupMembership entity.
type GroupMembershipCreate struct {
	config
	mutation *GroupMembershipMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (_c *GroupMembershipCreate) SetRole(v groupmembership.Role) *GroupMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableRole(v *groupmembership.Role) *GroupMembershipCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetAddedBy sets the "added_by" field.
func (_c *GroupMembershipCreate) SetAddedBy(v string) *GroupMembershipCreate {
	_c.mutation.SetAddedBy(v)
	return _c
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableAddedBy(v *string) *GroupMembershipCreate {
	if v != nil {
		_c.SetAddedBy(*v)
	}
	return _c
}

// SetAddedAt sets the "added_at" field.
func (_c *GroupMembershipCreate) SetAddedAt(v time.Time) *GroupMembershipCreate {
	_c.mutation.SetAddedAt(v)
	return _c
}

// SetNillableAddedAt sets the "added_at" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableAddedAt(v *time.Time) *GroupMembershipCreate {
	if v != nil {
		_c.SetAddedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupMembershipCreate) SetGroupID(v uuid.UUID) *GroupMembershipCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GroupMembershipCreate) SetUserID(v uuid.UUID) *GroupMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableUserID(v *uuid.UUID) *GroupMembershipCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *GroupMembershipCreate) SetAgentID(v uuid.UUID) *GroupMembershipCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableAgentID(v *uuid.UUID) *GroupMembershipCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupMembershipCreate) SetID(v uuid.UUID) *GroupMembershipCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroupMembershipCreate) SetNillableID(v *uuid.UUID) *GroupMembershipCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupMembershipCreate) SetGroup(v *Group) *GroupMembershipCreate {
	return _c.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *GroupMembershipCreate) SetUser(v *User) *GroupMembershipCreate {
	return _c.SetUserID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_c *GroupMembershipCreate) SetAgent(v *Agent) *GroupMembershipCreate {
	return _c.SetAgentID(v.ID)
}

// Mutation returns the GroupMembershipMutation object of the builder.
func (_c *GroupMembershipCreate) Mutation() *GroupMembershipMutation {
	return _c.mutation
}

// Save creates the GroupMembership in the database.
func (_c *GroupMembershipCreate) Save(ctx context.Context) (*GroupMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupMembershipCreate) SaveX(ctx context.Context) *GroupMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupMembershipCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := groupmembership.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.AddedAt(); !ok {
		v := groupmembership.DefaultAddedAt()
		_c.mutation.SetAddedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := groupmembership.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupMembershipCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "GroupMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := groupmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "GroupMembership.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddedAt(); !ok {
		return &ValidationError{Name: "added_at", err: errors.New(`ent: missing required field "GroupMembership.added_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupMembership.group_id"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupMembership.group"`)}
	}
	return nil
}

func (_c *GroupMembershipCreate) sqlSave(ctx context.Context) (*GroupMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupMembershipCreate) createSpec() (*GroupMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupmembership.Table, sqlgraph.NewFieldSpec(groupmembership.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(groupmembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.AddedBy(); ok {
		_spec.SetField(groupmembership.FieldAddedBy, field.TypeString, value)
		_node.AddedBy = value
	}
	if value, ok := _c.mutation.AddedAt(); ok {
		_spec.SetField(groupmembership.FieldAddedAt, field.TypeTime, value)
		_node.AddedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmembership.GroupTable,
			Columns: []string{groupmembership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupmembership.UserTable,
			Columns: []string{groupmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupmembership.AgentTable,
			Columns: []string{groupmembership.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupMembershipCreateBulk is the builder for creating many GroupMembership entities in bulk.
type GroupMembershipCreateBulk struct {
	config
	err      error
	builders []*GroupMembershipCreate
}

// Save creates the GroupMembership entities in the database.
func (_c *GroupMembershipCreateBulk) Save(ctx context.Context) ([]*GroupMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupMembershipCreateBulk) SaveX(ctx context.Context) []*GroupMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
