// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// GroveUpdate is the builder for updating Grove entities.
type GroveUpdate struct {
	config
	hooks    []Hook
	mutation *GroveMutation
}

// Where appends a list predicates to the GroveUpdate builder.
func (_u *GroveUpdate) Where(ps ...predicate.Grove) *GroveUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GroveUpdate) SetName(v string) *GroveUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableName(v *string) *GroveUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *GroveUpdate) SetSlug(v string) *GroveUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableSlug(v *string) *GroveUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetGitRemote sets the "git_remote" field.
func (_u *GroveUpdate) SetGitRemote(v string) *GroveUpdate {
	_u.mutation.SetGitRemote(v)
	return _u
}

// SetNillableGitRemote sets the "git_remote" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableGitRemote(v *string) *GroveUpdate {
	if v != nil {
		_u.SetGitRemote(*v)
	}
	return _u
}

// ClearGitRemote clears the value of the "git_remote" field.
func (_u *GroveUpdate) ClearGitRemote() *GroveUpdate {
	_u.mutation.ClearGitRemote()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *GroveUpdate) SetLabels(v map[string]string) *GroveUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *GroveUpdate) ClearLabels() *GroveUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetAnnotations sets the "annotations" field.
func (_u *GroveUpdate) SetAnnotations(v map[string]string) *GroveUpdate {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *GroveUpdate) ClearAnnotations() *GroveUpdate {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GroveUpdate) SetUpdated(v time.Time) *GroveUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GroveUpdate) SetCreatedBy(v string) *GroveUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableCreatedBy(v *string) *GroveUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GroveUpdate) ClearCreatedBy() *GroveUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *GroveUpdate) SetOwnerID(v string) *GroveUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableOwnerID(v *string) *GroveUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *GroveUpdate) ClearOwnerID() *GroveUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *GroveUpdate) SetVisibility(v string) *GroveUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *GroveUpdate) SetNillableVisibility(v *string) *GroveUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_u *GroveUpdate) AddAgentIDs(ids ...uuid.UUID) *GroveUpdate {
	_u.mutation.AddAgentIDs(ids...)
	return _u
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_u *GroveUpdate) AddAgents(v ...*Agent) *GroveUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentIDs(ids...)
}

// Mutation returns the GroveMutation object of the builder.
func (_u *GroveUpdate) Mutation() *GroveMutation {
	return _u.mutation
}

// ClearAgents clears all "agents" edges to the Agent entity.
func (_u *GroveUpdate) ClearAgents() *GroveUpdate {
	_u.mutation.ClearAgents()
	return _u
}

// RemoveAgentIDs removes the "agents" edge to Agent entities by IDs.
func (_u *GroveUpdate) RemoveAgentIDs(ids ...uuid.UUID) *GroveUpdate {
	_u.mutation.RemoveAgentIDs(ids...)
	return _u
}

// RemoveAgents removes "agents" edges to Agent entities.
func (_u *GroveUpdate) RemoveAgents(v ...*Agent) *GroveUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroveUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroveUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroveUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroveUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroveUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := grove.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroveUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := grove.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Grove.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := grove.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Grove.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *GroveUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grove.Table, grove.Columns, sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grove.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(grove.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitRemote(); ok {
		_spec.SetField(grove.FieldGitRemote, field.TypeString, value)
	}
	if _u.mutation.GitRemoteCleared() {
		_spec.ClearField(grove.FieldGitRemote, field.TypeString)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(grove.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(grove.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(grove.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(grove.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(grove.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(grove.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(grove.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(grove.FieldOwnerID, field.TypeString, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(grove.FieldOwnerID, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(grove.FieldVisibility, field.TypeString, value)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !_u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grove.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroveUpdateOne is the builder for updating a single Grove entity.
type GroveUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroveMutation
}

// SetName sets the "name" field.
func (_u *GroveUpdateOne) SetName(v string) *GroveUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableName(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *GroveUpdateOne) SetSlug(v string) *GroveUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableSlug(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetGitRemote sets the "git_remote" field.
func (_u *GroveUpdateOne) SetGitRemote(v string) *GroveUpdateOne {
	_u.mutation.SetGitRemote(v)
	return _u
}

// SetNillableGitRemote sets the "git_remote" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableGitRemote(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetGitRemote(*v)
	}
	return _u
}

// ClearGitRemote clears the value of the "git_remote" field.
func (_u *GroveUpdateOne) ClearGitRemote() *GroveUpdateOne {
	_u.mutation.ClearGitRemote()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *GroveUpdateOne) SetLabels(v map[string]string) *GroveUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *GroveUpdateOne) ClearLabels() *GroveUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetAnnotations sets the "annotations" field.
func (_u *GroveUpdateOne) SetAnnotations(v map[string]string) *GroveUpdateOne {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *GroveUpdateOne) ClearAnnotations() *GroveUpdateOne {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GroveUpdateOne) SetUpdated(v time.Time) *GroveUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GroveUpdateOne) SetCreatedBy(v string) *GroveUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableCreatedBy(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GroveUpdateOne) ClearCreatedBy() *GroveUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *GroveUpdateOne) SetOwnerID(v string) *GroveUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableOwnerID(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *GroveUpdateOne) ClearOwnerID() *GroveUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *GroveUpdateOne) SetVisibility(v string) *GroveUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *GroveUpdateOne) SetNillableVisibility(v *string) *GroveUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_u *GroveUpdateOne) AddAgentIDs(ids ...uuid.UUID) *GroveUpdateOne {
	_u.mutation.AddAgentIDs(ids...)
	return _u
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_u *GroveUpdateOne) AddAgents(v ...*Agent) *GroveUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentIDs(ids...)
}

// Mutation returns the GroveMutation object of the builder.
func (_u *GroveUpdateOne) Mutation() *GroveMutation {
	return _u.mutation
}

// ClearAgents clears all "agents" edges to the Agent entity.
func (_u *GroveUpdateOne) ClearAgents() *GroveUpdateOne {
	_u.mutation.ClearAgents()
	return _u
}

// RemoveAgentIDs removes the "agents" edge to Agent entities by IDs.
func (_u *GroveUpdateOne) RemoveAgentIDs(ids ...uuid.UUID) *GroveUpdateOne {
	_u.mutation.RemoveAgentIDs(ids...)
	return _u
}

// RemoveAgents removes "agents" edges to Agent entities.
func (_u *GroveUpdateOne) RemoveAgents(v ...*Agent) *GroveUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentIDs(ids...)
}

// Where appends a list predicates to the GroveUpdate builder.
func (_u *GroveUpdateOne) Where(ps ...predicate.Grove) *GroveUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroveUpdateOne) Select(field string, fields ...string) *GroveUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Grove entity.
func (_u *GroveUpdateOne) Save(ctx context.Context) (*Grove, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroveUpdateOne) SaveX(ctx context.Context) *Grove {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroveUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroveUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroveUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := grove.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroveUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := grove.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Grove.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := grove.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Grove.slug": %w`, err)}
		}
	}
	return nil
}

func (_u *GroveUpdateOne) sqlSave(ctx context.Context) (_node *Grove, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grove.Table, grove.Columns, sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Grove.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grove.FieldID)
		for _, f := range fields {
			if !grove.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grove.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grove.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(grove.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitRemote(); ok {
		_spec.SetField(grove.FieldGitRemote, field.TypeString, value)
	}
	if _u.mutation.GitRemoteCleared() {
		_spec.ClearField(grove.FieldGitRemote, field.TypeString)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(grove.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(grove.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(grove.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(grove.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(grove.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(grove.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(grove.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(grove.FieldOwnerID, field.TypeString, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(grove.FieldOwnerID, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(grove.FieldVisibility, field.TypeString, value)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !_u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Grove{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grove.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
