// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// PolicyBindingCreate is the builder for creating a PolicyBinding entity.
type PolicyBindingCreate struct {
	config
	mutation *PolicyBindingMutation
	hooks    []Hook
}

// SetPrincipalType sets the "principal_type" field.
func (_c *PolicyBindingCreate) SetPrincipalType(v policybinding.PrincipalType) *PolicyBindingCreate {
	_c.mutation.SetPrincipalType(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *PolicyBindingCreate) SetCreated(v time.Time) *PolicyBindingCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableCreated(v *time.Time) *PolicyBindingCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PolicyBindingCreate) SetCreatedBy(v string) *PolicyBindingCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableCreatedBy(v *string) *PolicyBindingCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetPolicyID sets the "policy_id" field.
func (_c *PolicyBindingCreate) SetPolicyID(v uuid.UUID) *PolicyBindingCreate {
	_c.mutation.SetPolicyID(v)
	return _c
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillablePolicyID(v *uuid.UUID) *PolicyBindingCreate {
	if v != nil {
		_c.SetPolicyID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PolicyBindingCreate) SetUserID(v uuid.UUID) *PolicyBindingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableUserID(v *uuid.UUID) *PolicyBindingCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PolicyBindingCreate) SetGroupID(v uuid.UUID) *PolicyBindingCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableGroupID(v *uuid.UUID) *PolicyBindingCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *PolicyBindingCreate) SetAgentID(v uuid.UUID) *PolicyBindingCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableAgentID(v *uuid.UUID) *PolicyBindingCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PolicyBindingCreate) SetID(v uuid.UUID) *PolicyBindingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PolicyBindingCreate) SetNillableID(v *uuid.UUID) *PolicyBindingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPolicy sets the "policy" edge to the AccessPolicy entity.
func (_c *PolicyBindingCreate) SetPolicy(v *AccessPolicy) *PolicyBindingCreate {
	return _c.SetPolicyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *PolicyBindingCreate) SetUser(v *User) *PolicyBindingCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *PolicyBindingCreate) SetGroup(v *Group) *PolicyBindingCreate {
	return _c.SetGroupID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_c *PolicyBindingCreate) SetAgent(v *Agent) *PolicyBindingCreate {
	return _c.SetAgentID(v.ID)
}

// Mutation returns the PolicyBindingMutation object of the builder.
func (_c *PolicyBindingCreate) Mutation() *PolicyBindingMutation {
	return _c.mutation
}

// Save creates the PolicyBinding in the database.
func (_c *PolicyBindingCreate) Save(ctx context.Context) (*PolicyBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PolicyBindingCreate) SaveX(ctx context.Context) *PolicyBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PolicyBindingCreate) defaults() {
	if _, ok := _c.mutation.Created(); !ok {
		v := policybinding.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := policybinding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PolicyBindingCreate) check() error {
	if _, ok := _c.mutation.PrincipalType(); !ok {
		return &ValidationError{Name: "principal_type", err: errors.New(`ent: missing required field "PolicyBinding.principal_type"`)}
	}
	if v, ok := _c.mutation.PrincipalType(); ok {
		if err := policybinding.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "PolicyBinding.principal_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "PolicyBinding.created"`)}
	}
	return nil
}

func (_c *PolicyBindingCreate) sqlSave(ctx context.Context) (*PolicyBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PolicyBindingCreate) createSpec() (*PolicyBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &PolicyBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(policybinding.Table, sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PrincipalType(); ok {
		_spec.SetField(policybinding.FieldPrincipalType, field.TypeEnum, value)
		_node.PrincipalType = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(policybinding.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(policybinding.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policybinding.PolicyTable,
			Columns: []string{policybinding.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PolicyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.UserTable,
			Columns: []string{policybinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.GroupTable,
			Columns: []string{policybinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.AgentTable,
			Columns: []string{policybinding.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PolicyBindingCreateBulk is the builder for creating many PolicyBinding entities in bulk.
type PolicyBindingCreateBulk struct {
	config
	err      error
	builders []*PolicyBindingCreate
}

// Save creates the PolicyBinding entities in the database.
func (_c *PolicyBindingCreateBulk) Save(ctx context.Context) ([]*PolicyBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PolicyBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PolicyBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PolicyBindingCreateBulk) SaveX(ctx context.Context) []*PolicyBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
