// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// PolicyBindingUpdate is the builder for updating PolicyBinding entities.
type PolicyBindingUpdate struct {
	config
	hooks    []Hook
	mutation *PolicyBindingMutation
}

// Where appends a list predicates to the PolicyBindingUpdate builder.
func (_u *PolicyBindingUpdate) Where(ps ...predicate.PolicyBinding) *PolicyBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrincipalType sets the "principal_type" field.
func (_u *PolicyBindingUpdate) SetPrincipalType(v policybinding.PrincipalType) *PolicyBindingUpdate {
	_u.mutation.SetPrincipalType(v)
	return _u
}

// SetNillablePrincipalType sets the "principal_type" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillablePrincipalType(v *policybinding.PrincipalType) *PolicyBindingUpdate {
	if v != nil {
		_u.SetPrincipalType(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PolicyBindingUpdate) SetCreatedBy(v string) *PolicyBindingUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillableCreatedBy(v *string) *PolicyBindingUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PolicyBindingUpdate) ClearCreatedBy() *PolicyBindingUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyBindingUpdate) SetPolicyID(v uuid.UUID) *PolicyBindingUpdate {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillablePolicyID(v *uuid.UUID) *PolicyBindingUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// ClearPolicyID clears the value of the "policy_id" field.
func (_u *PolicyBindingUpdate) ClearPolicyID() *PolicyBindingUpdate {
	_u.mutation.ClearPolicyID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PolicyBindingUpdate) SetUserID(v uuid.UUID) *PolicyBindingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillableUserID(v *uuid.UUID) *PolicyBindingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PolicyBindingUpdate) ClearUserID() *PolicyBindingUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PolicyBindingUpdate) SetGroupID(v uuid.UUID) *PolicyBindingUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillableGroupID(v *uuid.UUID) *PolicyBindingUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PolicyBindingUpdate) ClearGroupID() *PolicyBindingUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *PolicyBindingUpdate) SetAgentID(v uuid.UUID) *PolicyBindingUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *PolicyBindingUpdate) SetNillableAgentID(v *uuid.UUID) *PolicyBindingUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *PolicyBindingUpdate) ClearAgentID() *PolicyBindingUpdate {
	_u.mutation.ClearAgentID()
	return _u
}

// SetPolicy sets the "policy" edge to the AccessPolicy entity.
func (_u *PolicyBindingUpdate) SetPolicy(v *AccessPolicy) *PolicyBindingUpdate {
	return _u.SetPolicyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PolicyBindingUpdate) SetUser(v *User) *PolicyBindingUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PolicyBindingUpdate) SetGroup(v *Group) *PolicyBindingUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *PolicyBindingUpdate) SetAgent(v *Agent) *PolicyBindingUpdate {
	return _u.SetAgentID(v.ID)
}

// Mutation returns the PolicyBindingMutation object of the builder.
func (_u *PolicyBindingUpdate) Mutation() *PolicyBindingMutation {
	return _u.mutation
}

// ClearPolicy clears the "policy" edge to the AccessPolicy entity.
func (_u *PolicyBindingUpdate) ClearPolicy() *PolicyBindingUpdate {
	_u.mutation.ClearPolicy()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PolicyBindingUpdate) ClearUser() *PolicyBindingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PolicyBindingUpdate) ClearGroup() *PolicyBindingUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *PolicyBindingUpdate) ClearAgent() *PolicyBindingUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicyBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicyBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyBindingUpdate) check() error {
	if v, ok := _u.mutation.PrincipalType(); ok {
		if err := policybinding.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "PolicyBinding.principal_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicyBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policybinding.Table, policybinding.Columns, sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrincipalType(); ok {
		_spec.SetField(policybinding.FieldPrincipalType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(policybinding.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(policybinding.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policybinding.PolicyTable,
			Columns: []string{policybinding.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policybinding.PolicyTable,
			Columns: []string{policybinding.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.UserTable,
			Columns: []string{policybinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.UserTable,
			Columns: []string{policybinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.GroupTable,
			Columns: []string{policybinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.GroupTable,
			Columns: []string{policybinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.AgentTable,
			Columns: []string{policybinding.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.AgentTable,
			Columns: []string{policybinding.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policybinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicyBindingUpdateOne is the builder for updating a single PolicyBinding entity.
type PolicyBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicyBindingMutation
}

// SetPrincipalType sets the "principal_type" field.
func (_u *PolicyBindingUpdateOne) SetPrincipalType(v policybinding.PrincipalType) *PolicyBindingUpdateOne {
	_u.mutation.SetPrincipalType(v)
	return _u
}

// SetNillablePrincipalType sets the "principal_type" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillablePrincipalType(v *policybinding.PrincipalType) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetPrincipalType(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PolicyBindingUpdateOne) SetCreatedBy(v string) *PolicyBindingUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillableCreatedBy(v *string) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PolicyBindingUpdateOne) ClearCreatedBy() *PolicyBindingUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyBindingUpdateOne) SetPolicyID(v uuid.UUID) *PolicyBindingUpdateOne {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillablePolicyID(v *uuid.UUID) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// ClearPolicyID clears the value of the "policy_id" field.
func (_u *PolicyBindingUpdateOne) ClearPolicyID() *PolicyBindingUpdateOne {
	_u.mutation.ClearPolicyID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PolicyBindingUpdateOne) SetUserID(v uuid.UUID) *PolicyBindingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillableUserID(v *uuid.UUID) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *PolicyBindingUpdateOne) ClearUserID() *PolicyBindingUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PolicyBindingUpdateOne) SetGroupID(v uuid.UUID) *PolicyBindingUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillableGroupID(v *uuid.UUID) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PolicyBindingUpdateOne) ClearGroupID() *PolicyBindingUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *PolicyBindingUpdateOne) SetAgentID(v uuid.UUID) *PolicyBindingUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *PolicyBindingUpdateOne) SetNillableAgentID(v *uuid.UUID) *PolicyBindingUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *PolicyBindingUpdateOne) ClearAgentID() *PolicyBindingUpdateOne {
	_u.mutation.ClearAgentID()
	return _u
}

// SetPolicy sets the "policy" edge to the AccessPolicy entity.
func (_u *PolicyBindingUpdateOne) SetPolicy(v *AccessPolicy) *PolicyBindingUpdateOne {
	return _u.SetPolicyID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PolicyBindingUpdateOne) SetUser(v *User) *PolicyBindingUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PolicyBindingUpdateOne) SetGroup(v *Group) *PolicyBindingUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *PolicyBindingUpdateOne) SetAgent(v *Agent) *PolicyBindingUpdateOne {
	return _u.SetAgentID(v.ID)
}

// Mutation returns the PolicyBindingMutation object of the builder.
func (_u *PolicyBindingUpdateOne) Mutation() *PolicyBindingMutation {
	return _u.mutation
}

// ClearPolicy clears the "policy" edge to the AccessPolicy entity.
func (_u *PolicyBindingUpdateOne) ClearPolicy() *PolicyBindingUpdateOne {
	_u.mutation.ClearPolicy()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PolicyBindingUpdateOne) ClearUser() *PolicyBindingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PolicyBindingUpdateOne) ClearGroup() *PolicyBindingUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *PolicyBindingUpdateOne) ClearAgent() *PolicyBindingUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// Where appends a list predicates to the PolicyBindingUpdate builder.
func (_u *PolicyBindingUpdateOne) Where(ps ...predicate.PolicyBinding) *PolicyBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicyBindingUpdateOne) Select(field string, fields ...string) *PolicyBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PolicyBinding entity.
func (_u *PolicyBindingUpdateOne) Save(ctx context.Context) (*PolicyBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyBindingUpdateOne) SaveX(ctx context.Context) *PolicyBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicyBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyBindingUpdateOne) check() error {
	if v, ok := _u.mutation.PrincipalType(); ok {
		if err := policybinding.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "PolicyBinding.principal_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicyBindingUpdateOne) sqlSave(ctx context.Context) (_node *PolicyBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policybinding.Table, policybinding.Columns, sqlgraph.NewFieldSpec(policybinding.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PolicyBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policybinding.FieldID)
		for _, f := range fields {
			if !policybinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != policybinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PrincipalType(); ok {
		_spec.SetField(policybinding.FieldPrincipalType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(policybinding.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(policybinding.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policybinding.PolicyTable,
			Columns: []string{policybinding.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policybinding.PolicyTable,
			Columns: []string{policybinding.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.UserTable,
			Columns: []string{policybinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.UserTable,
			Columns: []string{policybinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.GroupTable,
			Columns: []string{policybinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.GroupTable,
			Columns: []string{policybinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.AgentTable,
			Columns: []string{policybinding.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   policybinding.AgentTable,
			Columns: []string{policybinding.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PolicyBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policybinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
