// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// PolicyBinding is the model entity for the PolicyBinding schema.
type PolicyBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PrincipalType holds the value of the "principal_type" field.
	PrincipalType policybinding.PrincipalType `json:"principal_type,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// PolicyID holds the value of the "policy_id" field.
	PolicyID *uuid.UUID `json:"policy_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *uuid.UUID `json:"group_id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID *uuid.UUID `json:"agent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PolicyBindingQuery when eager-loading is set.
	Edges        PolicyBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PolicyBindingEdges holds the relations/edges for other nodes in the graph.
type PolicyBindingEdges struct {
	// Policy holds the value of the policy edge.
	Policy *AccessPolicy `json:"policy,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Agent holds the value of the agent edge.
	Agent *Agent `json:"agent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PolicyOrErr returns the Policy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyBindingEdges) PolicyOrErr() (*AccessPolicy, error) {
	if e.Policy != nil {
		return e.Policy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: accesspolicy.Label}
	}
	return nil, &NotLoadedError{edge: "policy"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyBindingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyBindingEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// AgentOrErr returns the Agent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyBindingEdges) AgentOrErr() (*Agent, error) {
	if e.Agent != nil {
		return e.Agent, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "agent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PolicyBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case policybinding.FieldPolicyID, policybinding.FieldUserID, policybinding.FieldGroupID, policybinding.FieldAgentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case policybinding.FieldPrincipalType, policybinding.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case policybinding.FieldCreated:
			values[i] = new(sql.NullTime)
		case policybinding.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PolicyBinding fields.
func (_m *PolicyBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case policybinding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case policybinding.FieldPrincipalType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field principal_type", values[i])
			} else if value.Valid {
				_m.PrincipalType = policybinding.PrincipalType(value.String)
			}
		case policybinding.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case policybinding.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case policybinding.FieldPolicyID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field policy_id", values[i])
			} else if value.Valid {
				_m.PolicyID = new(uuid.UUID)
				*_m.PolicyID = *value.S.(*uuid.UUID)
			}
		case policybinding.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		case policybinding.FieldGroupID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(uuid.UUID)
				*_m.GroupID = *value.S.(*uuid.UUID)
			}
		case policybinding.FieldAgentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = new(uuid.UUID)
				*_m.AgentID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PolicyBinding.
// This includes values selected through modifiers, order, etc.
func (_m *PolicyBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPolicy queries the "policy" edge of the PolicyBinding entity.
func (_m *PolicyBinding) QueryPolicy() *AccessPolicyQuery {
	return NewPolicyBindingClient(_m.config).QueryPolicy(_m)
}

// QueryUser queries the "user" edge of the PolicyBinding entity.
func (_m *PolicyBinding) QueryUser() *UserQuery {
	return NewPolicyBindingClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the PolicyBinding entity.
func (_m *PolicyBinding) QueryGroup() *GroupQuery {
	return NewPolicyBindingClient(_m.config).QueryGroup(_m)
}

// QueryAgent queries the "agent" edge of the PolicyBinding entity.
func (_m *PolicyBinding) QueryAgent() *AgentQuery {
	return NewPolicyBindingClient(_m.config).QueryAgent(_m)
}

// Update returns a builder for updating this PolicyBinding.
// Note that you need to call PolicyBinding.Unwrap() before calling this method if this PolicyBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PolicyBinding) Update() *PolicyBindingUpdateOne {
	return NewPolicyBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PolicyBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PolicyBinding) Unwrap() *PolicyBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PolicyBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PolicyBinding) String() string {
	var builder strings.Builder
	builder.WriteString("PolicyBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("principal_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalType))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	if v := _m.PolicyID; v != nil {
		builder.WriteString("policy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AgentID; v != nil {
		builder.WriteString("agent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PolicyBindings is a parsable slice of PolicyBinding.
type PolicyBindings []*PolicyBinding
