// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/GoogleCloudPlatform/scion/pkg/ent/accesspolicy"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/group"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/groupmembership"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/policybinding"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/schema"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accesspolicyFields := schema.AccessPolicy{}.Fields()
	_ = accesspolicyFields
	// accesspolicyDescName is the schema descriptor for name field.
	accesspolicyDescName := accesspolicyFields[1].Descriptor()
	// accesspolicy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	accesspolicy.NameValidator = accesspolicyDescName.Validators[0].(func(string) error)
	// accesspolicyDescResourceType is the schema descriptor for resource_type field.
	accesspolicyDescResourceType := accesspolicyFields[5].Descriptor()
	// accesspolicy.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	accesspolicy.ResourceTypeValidator = accesspolicyDescResourceType.Validators[0].(func(string) error)
	// accesspolicyDescPriority is the schema descriptor for priority field.
	accesspolicyDescPriority := accesspolicyFields[10].Descriptor()
	// accesspolicy.DefaultPriority holds the default value on creation for the priority field.
	accesspolicy.DefaultPriority = accesspolicyDescPriority.Default.(int)
	// accesspolicyDescCreated is the schema descriptor for created field.
	accesspolicyDescCreated := accesspolicyFields[13].Descriptor()
	// accesspolicy.DefaultCreated holds the default value on creation for the created field.
	accesspolicy.DefaultCreated = accesspolicyDescCreated.Default.(func() time.Time)
	// accesspolicyDescUpdated is the schema descriptor for updated field.
	accesspolicyDescUpdated := accesspolicyFields[14].Descriptor()
	// accesspolicy.DefaultUpdated holds the default value on creation for the updated field.
	accesspolicy.DefaultUpdated = accesspolicyDescUpdated.Default.(func() time.Time)
	// accesspolicy.UpdateDefaultUpdated holds the default value on update for the updated field.
	accesspolicy.UpdateDefaultUpdated = accesspolicyDescUpdated.UpdateDefault.(func() time.Time)
	// accesspolicyDescID is the schema descriptor for id field.
	accesspolicyDescID := accesspolicyFields[0].Descriptor()
	// accesspolicy.DefaultID holds the default value on creation for the id field.
	accesspolicy.DefaultID = accesspolicyDescID.Default.(func() uuid.UUID)
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescSlug is the schema descriptor for slug field.
	agentDescSlug := agentFields[1].Descriptor()
	// agent.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	agent.SlugValidator = agentDescSlug.Validators[0].(func(string) error)
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[2].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescDelegationEnabled is the schema descriptor for delegation_enabled field.
	agentDescDelegationEnabled := agentFields[8].Descriptor()
	// agent.DefaultDelegationEnabled holds the default value on creation for the delegation_enabled field.
	agent.DefaultDelegationEnabled = agentDescDelegationEnabled.Default.(bool)
	// agentDescVisibility is the schema descriptor for visibility field.
	agentDescVisibility := agentFields[9].Descriptor()
	// agent.DefaultVisibility holds the default value on creation for the visibility field.
	agent.DefaultVisibility = agentDescVisibility.Default.(string)
	// agentDescCreated is the schema descriptor for created field.
	agentDescCreated := agentFields[10].Descriptor()
	// agent.DefaultCreated holds the default value on creation for the created field.
	agent.DefaultCreated = agentDescCreated.Default.(func() time.Time)
	// agentDescUpdated is the schema descriptor for updated field.
	agentDescUpdated := agentFields[11].Descriptor()
	// agent.DefaultUpdated holds the default value on creation for the updated field.
	agent.DefaultUpdated = agentDescUpdated.Default.(func() time.Time)
	// agent.UpdateDefaultUpdated holds the default value on update for the updated field.
	agent.UpdateDefaultUpdated = agentDescUpdated.UpdateDefault.(func() time.Time)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[1].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescSlug is the schema descriptor for slug field.
	groupDescSlug := groupFields[2].Descriptor()
	// group.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	group.SlugValidator = groupDescSlug.Validators[0].(func(string) error)
	// groupDescCreated is the schema descriptor for created field.
	groupDescCreated := groupFields[8].Descriptor()
	// group.DefaultCreated holds the default value on creation for the created field.
	group.DefaultCreated = groupDescCreated.Default.(func() time.Time)
	// groupDescUpdated is the schema descriptor for updated field.
	groupDescUpdated := groupFields[9].Descriptor()
	// group.DefaultUpdated holds the default value on creation for the updated field.
	group.DefaultUpdated = groupDescUpdated.Default.(func() time.Time)
	// group.UpdateDefaultUpdated holds the default value on update for the updated field.
	group.UpdateDefaultUpdated = groupDescUpdated.UpdateDefault.(func() time.Time)
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	groupmembershipFields := schema.GroupMembership{}.Fields()
	_ = groupmembershipFields
	// groupmembershipDescAddedAt is the schema descriptor for added_at field.
	groupmembershipDescAddedAt := groupmembershipFields[3].Descriptor()
	// groupmembership.DefaultAddedAt holds the default value on creation for the added_at field.
	groupmembership.DefaultAddedAt = groupmembershipDescAddedAt.Default.(func() time.Time)
	// groupmembershipDescID is the schema descriptor for id field.
	groupmembershipDescID := groupmembershipFields[0].Descriptor()
	// groupmembership.DefaultID holds the default value on creation for the id field.
	groupmembership.DefaultID = groupmembershipDescID.Default.(func() uuid.UUID)
	groveFields := schema.Grove{}.Fields()
	_ = groveFields
	// groveDescName is the schema descriptor for name field.
	groveDescName := groveFields[1].Descriptor()
	// grove.NameValidator is a validator for the "name" field. It is called by the builders before save.
	grove.NameValidator = groveDescName.Validators[0].(func(string) error)
	// groveDescSlug is the schema descriptor for slug field.
	groveDescSlug := groveFields[2].Descriptor()
	// grove.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	grove.SlugValidator = groveDescSlug.Validators[0].(func(string) error)
	// groveDescCreated is the schema descriptor for created field.
	groveDescCreated := groveFields[6].Descriptor()
	// grove.DefaultCreated holds the default value on creation for the created field.
	grove.DefaultCreated = groveDescCreated.Default.(func() time.Time)
	// groveDescUpdated is the schema descriptor for updated field.
	groveDescUpdated := groveFields[7].Descriptor()
	// grove.DefaultUpdated holds the default value on creation for the updated field.
	grove.DefaultUpdated = groveDescUpdated.Default.(func() time.Time)
	// grove.UpdateDefaultUpdated holds the default value on update for the updated field.
	grove.UpdateDefaultUpdated = groveDescUpdated.UpdateDefault.(func() time.Time)
	// groveDescVisibility is the schema descriptor for visibility field.
	groveDescVisibility := groveFields[10].Descriptor()
	// grove.DefaultVisibility holds the default value on creation for the visibility field.
	grove.DefaultVisibility = groveDescVisibility.Default.(string)
	// groveDescID is the schema descriptor for id field.
	groveDescID := groveFields[0].Descriptor()
	// grove.DefaultID holds the default value on creation for the id field.
	grove.DefaultID = groveDescID.Default.(func() uuid.UUID)
	policybindingFields := schema.PolicyBinding{}.Fields()
	_ = policybindingFields
	// policybindingDescCreated is the schema descriptor for created field.
	policybindingDescCreated := policybindingFields[2].Descriptor()
	// policybinding.DefaultCreated holds the default value on creation for the created field.
	policybinding.DefaultCreated = policybindingDescCreated.Default.(func() time.Time)
	// policybindingDescID is the schema descriptor for id field.
	policybindingDescID := policybindingFields[0].Descriptor()
	// policybinding.DefaultID holds the default value on creation for the id field.
	policybinding.DefaultID = policybindingDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescCreated is the schema descriptor for created field.
	userDescCreated := userFields[7].Descriptor()
	// user.DefaultCreated holds the default value on creation for the created field.
	user.DefaultCreated = userDescCreated.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
