// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessPoliciesColumns holds the columns for the "access_policies" table.
	AccessPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "scope_type", Type: field.TypeEnum, Enums: []string{"hub", "grove", "resource"}},
		{Name: "scope_id", Type: field.TypeString, Nullable: true},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString, Nullable: true},
		{Name: "actions", Type: field.TypeJSON, Nullable: true},
		{Name: "effect", Type: field.TypeEnum, Enums: []string{"allow", "deny"}},
		{Name: "conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "annotations", Type: field.TypeJSON, Nullable: true},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
	}
	// AccessPoliciesTable holds the schema information for the "access_policies" table.
	AccessPoliciesTable = &schema.Table{
		Name:       "access_policies",
		Columns:    AccessPoliciesColumns,
		PrimaryKey: []*schema.Column{AccessPoliciesColumns[0]},
	}
	// AgentsColumns holds the columns for the "agents" table.
	AgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "slug", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "template", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"created", "provisioning", "cloning", "starting", "running", "stopping", "stopped", "error"}, Default: "created"},
		{Name: "delegation_enabled", Type: field.TypeBool, Default: false},
		{Name: "visibility", Type: field.TypeString, Default: "private"},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
		{Name: "grove_id", Type: field.TypeUUID},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID, Nullable: true},
	}
	// AgentsTable holds the schema information for the "agents" table.
	AgentsTable = &schema.Table{
		Name:       "agents",
		Columns:    AgentsColumns,
		PrimaryKey: []*schema.Column{AgentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "agents_groves_agents",
				Columns:    []*schema.Column{AgentsColumns[9]},
				RefColumns: []*schema.Column{GrovesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "agents_users_created_agents",
				Columns:    []*schema.Column{AgentsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "agents_users_owned_agents",
				Columns:    []*schema.Column{AgentsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "agent_slug_grove_id",
				Unique:  true,
				Columns: []*schema.Column{AgentsColumns[1], AgentsColumns[9]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "group_type", Type: field.TypeEnum, Enums: []string{"explicit", "grove_agents"}, Default: "explicit"},
		{Name: "grove_id", Type: field.TypeUUID, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "annotations", Type: field.TypeJSON, Nullable: true},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID, Nullable: true},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_users_owned_groups",
				Columns:    []*schema.Column{GroupsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GroupMembershipsColumns holds the columns for the "group_memberships" table.
	GroupMembershipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"member", "admin", "owner"}, Default: "member"},
		{Name: "added_by", Type: field.TypeString, Nullable: true},
		{Name: "added_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "agent_id", Type: field.TypeUUID, Nullable: true},
	}
	// GroupMembershipsTable holds the schema information for the "group_memberships" table.
	GroupMembershipsTable = &schema.Table{
		Name:       "group_memberships",
		Columns:    GroupMembershipsColumns,
		PrimaryKey: []*schema.Column{GroupMembershipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_memberships_groups_memberships",
				Columns:    []*schema.Column{GroupMembershipsColumns[4]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "group_memberships_users_user",
				Columns:    []*schema.Column{GroupMembershipsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "group_memberships_agents_agent",
				Columns:    []*schema.Column{GroupMembershipsColumns[6]},
				RefColumns: []*schema.Column{AgentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupmembership_group_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMembershipsColumns[4], GroupMembershipsColumns[5]},
			},
			{
				Name:    "groupmembership_group_id_agent_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMembershipsColumns[4], GroupMembershipsColumns[6]},
			},
		},
	}
	// GrovesColumns holds the columns for the "groves" table.
	GrovesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "git_remote", Type: field.TypeString, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "annotations", Type: field.TypeJSON, Nullable: true},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "owner_id", Type: field.TypeString, Nullable: true},
		{Name: "visibility", Type: field.TypeString, Default: "private"},
	}
	// GrovesTable holds the schema information for the "groves" table.
	GrovesTable = &schema.Table{
		Name:       "groves",
		Columns:    GrovesColumns,
		PrimaryKey: []*schema.Column{GrovesColumns[0]},
	}
	// PolicyBindingsColumns holds the columns for the "policy_bindings" table.
	PolicyBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "principal_type", Type: field.TypeEnum, Enums: []string{"user", "agent", "group"}},
		{Name: "created", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "policy_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "group_id", Type: field.TypeUUID, Nullable: true},
		{Name: "agent_id", Type: field.TypeUUID, Nullable: true},
	}
	// PolicyBindingsTable holds the schema information for the "policy_bindings" table.
	PolicyBindingsTable = &schema.Table{
		Name:       "policy_bindings",
		Columns:    PolicyBindingsColumns,
		PrimaryKey: []*schema.Column{PolicyBindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "policy_bindings_access_policies_bindings",
				Columns:    []*schema.Column{PolicyBindingsColumns[4]},
				RefColumns: []*schema.Column{AccessPoliciesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "policy_bindings_users_user",
				Columns:    []*schema.Column{PolicyBindingsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "policy_bindings_groups_group",
				Columns:    []*schema.Column{PolicyBindingsColumns[6]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "policy_bindings_agents_agent",
				Columns:    []*schema.Column{PolicyBindingsColumns[7]},
				RefColumns: []*schema.Column{AgentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member", "viewer"}, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "suspended"}, Default: "active"},
		{Name: "preferences", Type: field.TypeJSON, Nullable: true},
		{Name: "created", Type: field.TypeTime},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// GroupChildGroupsColumns holds the columns for the "group_child_groups" table.
	GroupChildGroupsColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeUUID},
		{Name: "parent_group_id", Type: field.TypeUUID},
	}
	// GroupChildGroupsTable holds the schema information for the "group_child_groups" table.
	GroupChildGroupsTable = &schema.Table{
		Name:       "group_child_groups",
		Columns:    GroupChildGroupsColumns,
		PrimaryKey: []*schema.Column{GroupChildGroupsColumns[0], GroupChildGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_child_groups_group_id",
				Columns:    []*schema.Column{GroupChildGroupsColumns[0]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_child_groups_parent_group_id",
				Columns:    []*schema.Column{GroupChildGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessPoliciesTable,
		AgentsTable,
		GroupsTable,
		GroupMembershipsTable,
		GrovesTable,
		PolicyBindingsTable,
		UsersTable,
		GroupChildGroupsTable,
	}
)

func init() {
	AgentsTable.ForeignKeys[0].RefTable = GrovesTable
	AgentsTable.ForeignKeys[1].RefTable = UsersTable
	AgentsTable.ForeignKeys[2].RefTable = UsersTable
	GroupsTable.ForeignKeys[0].RefTable = UsersTable
	GroupMembershipsTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMembershipsTable.ForeignKeys[1].RefTable = UsersTable
	GroupMembershipsTable.ForeignKeys[2].RefTable = AgentsTable
	PolicyBindingsTable.ForeignKeys[0].RefTable = AccessPoliciesTable
	PolicyBindingsTable.ForeignKeys[1].RefTable = UsersTable
	PolicyBindingsTable.ForeignKeys[2].RefTable = GroupsTable
	PolicyBindingsTable.ForeignKeys[3].RefTable = AgentsTable
	GroupChildGroupsTable.ForeignKeys[0].RefTable = GroupsTable
	GroupChildGroupsTable.ForeignKeys[1].RefTable = GroupsTable
}
