from google.adk.agents import Agent, ParallelAgent, SequentialAgent
from google.adk.tools import google_search
from google.adk.agents import LlmAgent
# ==============================================================================
# HIERARCHICAL DECOMPOSITION (Nested "Russian Doll" Pattern)
# ==============================================================================
# In complex scenarios, you may want an orchestrator agent that autonomously
# drafts a plan and then delegates that plan to a specialized pipeline of
# sub-agents. 
#
# This uses the `AgentTool` concept. The Manager treats the Planner as a tool
# to get a structured plan, then activates its sub-agents to execute it.
# ==============================================================================
from google.adk.tools.agent_tool import AgentTool

# 1. THE PLANNER (Used as a tool)
planner = LlmAgent(
    name='planner',
    model='gemini-3-flash-preview',
    description='Breaks a complex prompt into distinct parts.',
    instruction='''
    You are an AI Architect Manager. Read the user's complex prompt and break it down into exactly three distinct research themes or chronological phases. 
    
    Output nothing but a numbered list:
    1. [Theme 1 Description]
    2. [Theme 2 Description]
    3. [Theme 3 Description]
    ''',
    # Tool agents write their output directly into a tool execution result,
    # rather than modifying the global ADK session memory.
)

# 2. THE EXECUTION PIPELINE (Sub-agents)
researcher = LlmAgent(
    name='researcher',
    model='gemini-3-flash-preview',
    description='Executes the research plan.',
    tools=[google_search],
    output_key='research_findings',
    instruction='''
    You are a meticulous researcher. The user will provide a 3-part research plan.
    Use the `google_search` tool to gather comprehensive information for ALL three themes in the plan.
    Synthesize your findings into a detailed research document.
    '''
)

synthesizer = LlmAgent(
    name='synthesizer',
    model='gemini-3-flash-preview',
    description='Writes the final report from research findings.',
    instruction='''
    You are the Lead Editor. Using the `research_findings` generated by the previous agent, synthesize a comprehensive, cohesive final report on the topic.
    
    # Research Findings
    {research_findings}
    '''
)

execution_pipeline = SequentialAgent(
    name='execution_pipeline',
    description='A logical pipeline that researches a plan and writes a final report.',
    sub_agents=[researcher, synthesizer]
)

# 3. THE MANAGER (Top-level orchestrator)
manager = LlmAgent(
    name='manager',
    model='gemini-3-flash-preview',
    description='The top-level orchestrator that plans and delegates.',
    tools=[AgentTool(planner)],
    sub_agents=[execution_pipeline],
    instruction='''
    You are the Director. Your strict workflow is:
    1. Use the `planner` tool to create a detailed research plan based on the user's initial prompt.
    2. Once you have the 3-part plan from the tool, ACTIVATE your `execution_pipeline` sub-agent.
    3. Pass the completed plan to the pipeline so it can research and synthesize a report.
    4. Return the comprehensive final synthesized report to the user. Do exactly what the user asks!
    '''
)

root_agent = manager

from google.adk.apps import App

app = App(
    name="hierarchical",
    root_agent=root_agent
)

if __name__ == '__main__':
    # Provided for local testing if running directly with `uv run python` instead of `adk run`
    import asyncio
    from google.adk.runners import InMemoryRunner

    async def run_demo():
        runner = InMemoryRunner(app=app)
        print("Starting Hierarchical Agent Demo...")
        await runner.run_debug("Research the evolution of generative AI in software engineering. Cover its historical roots, its current impact on standard IDEs, and predict what software engineering will look like 10 years from now.")

    asyncio.run(run_demo())
